object Version {
    const val GRADLE_BUILD_TOOLS = "8.4.0"
    const val KOTLIN = "1.9.24"
    const val GOOGLE_SERVICE = "4.3.15"
    const val MATERIAL = "1.8.0"
    const val RETROFIT = "2.9.0"
    const val OKHTTP_PROFILER = "1.0.8"
    const val CORE_KTX = "1.9.0"
    const val NAVIGATION_RUNTIME = "2.5.3"
    const val LIVECYCLE = "2.6.1"
    const val APP_COMPAT = "1.6.0"
    const val CONSTRAINT_LAYOUT = "2.1.0"
    const val LIFECYCLE_COMMON = "2.6.1"
    const val FRAGMENT_KTX = "1.6.0"
    const val NAVIGATION_KTX = "2.5.3"
    const val RECYCLER_VIEW = "1.3.0"
    const val KOIN_ANDROID = "3.4.0"
    const val KOIN_ANNOTATIONS = "1.3.0"
    const val GSON_CONVERTER = "2.9.0"
    const val LOGGING_INTERCEPTOR = "5.0.0-alpha.2"
    const val ROOM_VERSION = "2.6.1"
    const val NAV_VERSION = "2.5.3"
    const val LEGACY_SUPPORT = "1.0.0"
    const val COROUTINES = "1.6.4"
    const val JODATIME = "2.10.12.2"
    const val VIEW_BINDING = "1.5.9"
    const val LOTTIE_ANDROID = "3.7.0"
    const val KOTLINX_SERIALIZATION_JSON = "1.3.0"
    // test
    const val JUNIT = "4.13.2"
    const val ANDROIDX_JUNIT = "1.1.3"
    const val ANDROIDX_ESPRESSO_CORE = "3.4.0"
    const val COROUTINES_TEST = "1.5.1"
    const val ARCH_CORE_TESTING = "2.1.0"
}